CREATE TABLE IF NOT EXISTS quality_audit (
  audit_id BIGSERIAL PRIMARY KEY,
  event_type VARCHAR(120) NOT NULL,
  site VARCHAR(80) NOT NULL,
  role_name VARCHAR(80) NOT NULL,
  scenario VARCHAR(120) NOT NULL,
  simulated BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

